version: 1
accounts:
  - name: alice
    mnemonic: "slide moment original seven milk crawl help text kick fluid boring awkward doll wonder sure fragile plate grid hard next casual expire okay body"
    coins: ["200000000uspn","20000token", "200000000stake"]
  - name: bob
    mnemonic: "trap possible liquid elite embody host segment fantasy swim cable digital eager tiny broom burden diary earn hen grow engine pigeon fringe claim program"
    coins: ["200000000uspn","20000token", "200000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
    staked: "100000000uspn"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000uspn","5token", "100000stake"]
